---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: false  # Allow all checks to run even if one fails

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=600 ]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
        # .targets is an MSBuild XML extension, but ours is a Makefile
        exclude: ^dev/Makefile\.targets$
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: pretty-format-json
        args: [ --autofix ]
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        exclude: |
          (?x)(
            \.png$  |
            \.ico$
          )
      - id: git-check    # configure in .gitattributes
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      # Shell/bash scripts, detected by type and shebang.
      - id: shellcheck
        args: [ -a ]
      - id: shfmt
        args: [ -w, -i, "2", -s, -d ]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint

  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos
        args: [ --force-exclude ]

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: [ --number ]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-wikilink

  - repo: local
    hooks:
      - id: perlcritic
        name: perlcritic
        description: Ensure perl files adhere to standards
        language: system
        entry: perl -Ilib -S perlcritic lib t dev
        pass_filenames: false

      - id: jscpd
        name: Check for duplicated code
        description: Ensure we don't have large sections of duplicated code
        language: node
        entry: jscpd
        pass_filenames: false
        additional_dependencies:
          - jscpd@5.0.11
