.PHONY: show-authordeps install-authordeps reinstall-authordeps \
	show-deps install-deps reinstall-deps \
	t xt format lint clean build install \
	cover cover-html cover-compilation cover-nvim

show-authordeps:
	@dzil authordeps

install-authordeps:
	dzil authordeps --missing | cpm install -g -

reinstall-authordeps:
	dzil authordeps | cpm install -g --reinstall --no-prebuilt -

show-deps:
	@dzil listdeps --develop

install-deps:
	dzil listdeps --develop --missing | cpm install -g -

reinstall-deps:
	dzil listdeps --develop | cpm install -g --reinstall --no-prebuilt -

t:
	yath test -j20 --qvf --no-color -T --term-width=$(tput cols)

xt:
	dzil test
	dzil xt

format:
	@mkdir -p tmp/perltidy
	@git ls-files '*.pl' '*.pm' '*.t' | while read file; do \
		if perltidy -b -bext=tdybak "$$file" >/dev/null 2>&1; then \
			if [[ -f "$$file.tdybak" ]]; then \
				if ! diff -q "$$file" "$$file.tdybak" >/dev/null 2>&1; then \
					echo "Formatted $$file"; \
				fi; \
				mv "$$file.tdybak" tmp/perltidy/; \
			fi; \
		fi; \
	done

lint:
	pre-commit run --all-files

clean:
	dzil clean

build: clean
	dzil build

install: build
	dzil install

cover: build
	cover --delete
	HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,^t/ make t

cover-html: cover
	cover --report=html_basic --launch

cover-compilation: cover
	cover --report=compilation

cover-nvim: cover
	cover --report=nvim

cover-all: cover
	cover --report=nvim
	cover --report=compilation
